guide/config/routes.rb
Guide::Application.routes.draw do

  resources :restaurants

  root 'welcome#index'
  get "welcome/index"

end

guide/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

guide/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def new
		@restaurant = Restaurant.new
	end

	def create
		# render text: params[:restaurant].inspect
=begin
		@restaurant = Restaurant.new(params[:restaurant])
		@restaurant.save
		redirect_to @post
=end
		@restaurant = Restaurant.new(restaurant_params)

		if @restaurant.save
			redirect_to @restaurant
		else
			render 'new'
		end
    end

    def show
    	@restaurant = Restaurant.find(params[:id])
    end

    def index
    	@restaurant = Restaurant.all
    end

	def edit
 		 @restaurant = Restaurant.find(params[:id])
	end

	def update
	  @restaurant = Restaurant.find(params[:id])
	 
#	  if @restaurant.update(params[:restaurant].permit(:title, :text))
	  if @restaurant.update(params[:restaurant].permit(:name, :description))


	    redirect_to @restaurant
	  else
	    render 'edit'
	  end
	end	

	private
	def restaurant_params
		params.require(:restaurant).permit(:name, :description, :street_address, :city, :state, :zip_code, :phone_number)
	end


end

guide/app/helpers/application_helper.rb
module ApplicationHelper
end

guide/app/views/restaurants/_form.html.erb
<%= form_for @restaurant  do |f| %>
#<%= form_for :restaurant , url: restaurant_path, method: :patch do |f| %>

 <% if @restaurant.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited
      this Restaurant from being saved:</h2>
    <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :street_address %><br>
    <%= f.text_area :street_address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </p>

  <p>
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </p>

  <p>
    <%= f.label :zip_code %><br>
    <%= f.text_area :zip_code %>
  </p>

  <p>
    <%= f.label :phone_number %><br>
    <%= f.text_area :phone_number %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>

guide/app/views/restaurants/index.html.erb
<h1>Listing Restaurants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Street Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip Code</th>
    <th>Phone Number</th>
  </tr>
 
  <% @restaurant.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.description %></td>
      <td><%= restaurant.street_address %></td>
      <td><%= restaurant.city %></td>
      <td><%= restaurant.state %></td>
      <td><%= restaurant.zip_code %></td>
      <td><%= restaurant.phone_number %></td>
	  <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New', new_restaurant_path %>

guide/app/views/restaurants/show.html.erb
<h1>Show Restaurants</h1>
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @restaurant.description %>
</p>
 <p>
  <strong>Street Address:</strong>
  <%= @restaurant.street_address %>
</p>
 
<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @restaurant.state %>
</p>
 
<p>
  <strong>Zip Code:</strong>
  <%= @restaurant.zip_code %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @restaurant.phone_number %>
</p>
 
  <%= link_to 'Back', restaurants_path %>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>